# templates/secret-redis.yaml
{{- if and .Values.redis.enabled (not .Values.redis.external.enabled) .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mcp-stack.redisSecretName" . | trim }}"
type: Opaque
stringData:
  {{ .Values.redis.auth.passwordKey | default "REDIS_PASSWORD" }}: {{ .Values.redis.auth.password | quote }}
{{- end }}
